# Generated by Django 5.2.7 on 2025-10-27 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0013_create_auth_tables'),
        ('resources', '0005_remove_resource_resources_topic_ab76b4_idx'),
        ('studyplan', '0005_cleanup_unused_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_resources', models.IntegerField(default=0)),
                ('completed_resources', models.IntegerField(default=0)),
                ('total_hours_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('study_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='studyplan.studyplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='authentication.user')),
            ],
            options={
                'verbose_name_plural': 'Progress',
                'db_table': 'progress',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DecimalField(decimal_places=2, default=0.0, help_text='Session duration in hours', max_digits=8)),
                ('notes', models.TextField(blank=True, null=True)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_sessions', to='resources.resource')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='studyplan.studyplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='authentication.user')),
            ],
            options={
                'db_table': 'study_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_plan', 'Created First Study Plan'), ('first_completion', 'Completed First Resource'), ('plan_completed', 'Completed Study Plan'), ('streak_7', '7-Day Study Streak'), ('streak_30', '30-Day Study Streak'), ('hours_10', '10 Hours Studied'), ('hours_50', '50 Hours Studied'), ('hours_100', '100 Hours Studied'), ('resources_10', '10 Resources Completed'), ('resources_50', '50 Resources Completed')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='authentication.user')),
            ],
            options={
                'db_table': 'achievement',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement_type')},
            },
        ),
        migrations.CreateModel(
            name='ResourceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('time_spent', models.DecimalField(decimal_places=2, default=0.0, help_text='Hours spent on this resource', max_digits=8)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this resource', null=True)),
                ('study_plan_resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='studyplan.studyplanresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_progress', to='authentication.user')),
            ],
            options={
                'db_table': 'resource_progress',
                'ordering': ['study_plan_resource__order_index'],
                'unique_together': {('user', 'study_plan_resource')},
            },
        ),
    ]
