# Generated by Django 5.2.7 on 2025-11-15 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_user_last_login_date_user_login_streak_and_more'),
        ('quiz', '0002_alter_quiz_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to='authentication.user'),
        ),
    ]
