# Generated by Django 5.2.7 on 2025-11-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Make quiz available to users with same topic category'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='points_earned',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Points earned in this attempt', max_digits=10),
        ),
    ]
