# Generated by Django 5.2.8 on 2025-12-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='allow_retake',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='max_attempts',
        ),
        migrations.AddField(
            model_name='quiz',
            name='allow_review',
            field=models.BooleanField(default=True, help_text='Allow users to review and retake quiz after first attempt'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='passing_score',
            field=models.IntegerField(default=60, help_text='Passing score percentage'),
        ),
    ]
