# Generated by Django 5.2.8 on 2025-12-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_quiz_allow_retake_remove_quiz_max_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_retake',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
