# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_goals_alter_user_learningstyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='goals',
            field=models.TextField(default='To be determined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='learningstyle',
            field=models.CharField(default='Visual', max_length=50),
        ),
    ]
