# Generated by Django 5.2.7 on 2025-10-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_reset_token_user_reset_token_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='learningstyle',
            field=models.CharField(default='Visual', max_length=200),
        ),
    ]
