# Generated by Django 5.2.7 on 2025-10-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_learningstyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='learningstyle',
            field=models.CharField(default='Visual', max_length=50),
        ),
    ]
