# Generated by Django 5.2.7 on 2025-11-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_user_last_login_date_user_login_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
