# Generated by Django 5.2.7 on 2025-10-09 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_alter_user_goals_alter_user_learningstyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('learning_objective', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('preferred_resources', models.CharField(blank=True, help_text='e.g., Books, Videos, Online Courses', max_length=300, null=True)),
                ('estimated_hours_per_week', models.IntegerField(help_text='Estimated hours per week')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='authentication.user')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
