# Generated by Django 5.2.7 on 2025-10-11 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_is_external_alter_resource_is_free'),
        ('studyplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterModelTable(
            name='studyplan',
            table='studyplan',
        ),
        migrations.CreateModel(
            name='StudyPlanResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(default=0, help_text='Order of resource in study plan')),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='resources.resource')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_resources', to='studyplan.studyplan')),
            ],
            options={
                'db_table': 'studyplanresource',
                'ordering': ['order_index', 'id'],
                'unique_together': {('study_plan', 'resource')},
            },
        ),
    ]
