# Generated by Django 5.2.7 on 2025-10-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplan', '0002_studyplan_status_alter_studyplan_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='estimated_hours_per_week',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studyplanresource',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
    ]
