# Generated by Django 5.2.7 on 2025-10-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplan', '0005_cleanup_unused_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyplanresource',
            options={'ordering': ['priority', 'order_index', 'id']},
        ),
        migrations.AddField(
            model_name='studyplanresource',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
