# Generated by Django 5.2.7 on 2025-11-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplan', '0006_alter_studyplanresource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='topic_category',
            field=models.CharField(choices=[('', 'Select topic category...'), ('programming', 'Programming Languages'), ('web', 'Web Development'), ('mobile', 'Mobile Development'), ('data_science', 'Data Science & AI'), ('devops', 'DevOps & Cloud'), ('business', 'Business Management'), ('finance', 'Finance & Accounting'), ('marketing', 'Marketing'), ('leadership', 'Leadership & Management'), ('communication', 'Communication'), ('language_spanish', 'Spanish Language'), ('language_french', 'French Language'), ('language_german', 'German Language'), ('language_other', 'Other Languages'), ('biology', 'Biology'), ('chemistry', 'Chemistry'), ('physics', 'Physics'), ('mathematics', 'Mathematics'), ('art', 'Art & Design'), ('music', 'Music'), ('writing', 'Writing & Literature'), ('photography', 'Photography'), ('fitness', 'Fitness & Nutrition'), ('psychology', 'Psychology'), ('mindfulness', 'Mindfulness & Meditation'), ('other', 'Other Topic')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='preferred_resources',
            field=models.CharField(choices=[('', 'Select resource types...'), ('videos', 'Videos (YouTube, Coursera, Udemy)'), ('articles', 'Articles & Documentation'), ('interactive', 'Interactive Coding/Practice'), ('books', 'Books & eBooks'), ('courses', 'Structured Courses'), ('mixed', 'Mixed (Variety of above)')], default='mixed', help_text='Type of learning resources', max_length=50),
        ),
    ]
