# Generated by Django 5.2.7 on 2025-10-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, help_text='Main topic/subject area', max_length=200)),
                ('title', models.CharField(help_text='Resource title', max_length=300)),
                ('url', models.URLField(help_text='Direct link to resource', max_length=500, unique=True)),
                ('description', models.TextField(help_text='Why this resource is valuable')),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('practice', 'Practice/Interactive'), ('course', 'Online Course'), ('documentation', 'Documentation'), ('tutorial', 'Tutorial'), ('book', 'Book/E-book')], db_index=True, max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All Levels')], default='all', max_length=15)),
                ('platform', models.CharField(help_text='YouTube, freeCodeCamp, MDN, etc.', max_length=100)),
                ('learning_style', models.CharField(blank=True, help_text='Best suited for which learning style (optional)', max_length=50)),
                ('estimated_time', models.CharField(blank=True, help_text='Time to complete', max_length=50)),
                ('is_free', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', help_text='Resource language', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('times_recommended', models.IntegerField(default=0, help_text='How many times recommended by AI')),
            ],
            options={
                'db_table': 'resources',
                'ordering': ['-times_recommended', '-created_at'],
                'indexes': [models.Index(fields=['topic', 'resource_type'], name='resources_topic_2251d0_idx'), models.Index(fields=['topic', 'learning_style'], name='resources_topic_ab76b4_idx')],
            },
        ),
    ]
