# Generated by Django 5.2.7 on 2025-10-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_external',
            field=models.BooleanField(default=True, help_text='Is this an external resource (vs internal content)'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_free',
            field=models.BooleanField(default=True, help_text='Is resource free or paid'),
        ),
    ]
