# Generated by Django 5.2.7 on 2025-10-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_is_external_alter_resource_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_external',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='learning_style',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='platform',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='times_recommended',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='resource',
            name='topic',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
