# Generated by Django 5.2.7 on 2025-10-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resource_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('web_development', 'Web Development'), ('data_science', 'Data Science'), ('machine_learning', 'Machine Learning'), ('mobile_development', 'Mobile Development'), ('design', 'Design'), ('business', 'Business'), ('languages', 'Languages'), ('science', 'Science'), ('arts', 'Arts & Music'), ('cooking', 'Cooking'), ('fitness', 'Fitness'), ('other', 'Other')], db_index=True, default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='learning_style',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['category', 'learning_style'], name='resources_categor_82080d_idx'),
        ),
    ]
