# Generated by Django 5.2.7 on 2025-10-27 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resource_category_alter_resource_learning_style_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resource',
            name='resources_topic_ab76b4_idx',
        ),
    ]
