# Generated by Django 5.2.7 on 2025-10-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_remove_resource_resources_topic_ab76b4_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resource',
            name='resources_categor_82080d_idx',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='learning_style',
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['category'], name='resources_categor_ee9097_idx'),
        ),
    ]
